FROM node:4-onbuild

MAINTAINER Sean Macdonald <sean.macdonald@stjoseph.com>

#   Orchestra
ENV ORCHESTRA_PROJECT tester
ENV ORCHESTRA_APP dogs
ENV ORCHESTRA_SERVICE nodejs
LABEL io.sjc.orchestra.version="0.0.1"

EXPOSE 8888
